apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: demo-app-main2
  namespace: argocd

spec:
  project: my-project

  source:
    repoURL: https://github.com/hatif007/argo-demo-repo.git
    targetRevision: MAIN2
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true