apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: dynamic-applicationset
  namespace: argocd

spec:
  goTemplate: true

  generators:
    - git:
        repoURL: https://github.com/hatif007/argo-demo-repo.git
        revision: MAIN3

        directories:
          - path: 'my-project/*/qa'

  template:

    metadata:
      name: 'dynamic-{{index .path.segments 1}}-{{index .path.segments 2}}'

    spec:
      project: my-project

      source:
        repoURL: https://github.com/hatif007/argo-demo-repo.git
        targetRevision: MAIN3
        path: '{{.path.path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: 'dynamic-{{index .path.segments 1}}-{{index .path.segments 2}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true