apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: example-applicationset
  namespace: argocd

spec:

  generators:
    - git:
        repoURL: https://github.com/hatif007/argo-demo-repo.git
        revision: MAIN3

        directories:
          - path: '???'

  template:

    metadata:
      name: '???'

    spec:
      project: my-project

      source:
        repoURL: https://github.com/hatif007/argo-demo-repo.git
        targetRevision: MAIN3
        path: '???'

      destination:
        server: https://kubernetes.default.svc
        namespace: '???'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true