apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: example-applicationset
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - env: dev
            team: team-a
          - env: qa
            team: team-a

  template:
    metadata:
      name: '{{team}}-{{env}}'

    spec:
      project: my-project

      source:
        repoURL: https://github.com/hatif007/argo-demo-repo.git
        targetRevision: MAIN2
        path: my-project
        directory:
          include: 'team-a-{{env}}.yaml'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{team}}-{{env}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true