apiVersion: apps/v1
kind: Deployment

metadata:
  name: color-deploy

spec:
  replicas: 4

  selector:
    matchLabels:
      app: color

  template:
    metadata:
      labels:
        app: color

    spec:
      containers:
        - name: color
          image: elevy99927/color:yellow
          ports:
            - containerPort: 80