apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: my-project
  namespace: argocd

spec:
  description: My ArgoCD Project

  sourceRepos:
    - https://github.com/hatif007/argo-demo-repo.git
    - https://stefanprodan.github.io/podinfo

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  sourceNamespaces:
    - '*'